### ISSUE TITLE
画面設計をどうするか決める

### ISSUE THREAD

**Issue by tsumichan** [tsumichan/todo-app#1]
>ステップ4: 作りたいアプリケーションのイメージを考えよう
設計を進める前に、どのようなアプリになるか完成イメージを（メンターと一緒に）考えてみましょう。ペーパープロトタイピングによる画面設計などがおすすめです

紙に描いてみる

## システムの要件

- タスクに終了期限を設定できるようにしたい
- タスクに優先順位をつけたい
- ステータス（未着手・着手・完了）を管理したい
- ステータスでタスクを絞り込みたい
- タスク名・タスクの説明文でタスクを検索したい
- タスクを一覧したい。一覧画面で（優先順位、終了期限などを元にして）ソートしたい
- タスクにラベルなどをつけて分類したい
- ユーザ登録し、自分が登録したタスクだけを見られるようにしたい
- ユーザの管理機能

## 必要な画面

- [x] タスクの一覧
- [x] タスクの追加
- [x] タスクの編集
- [x] 管理画面
- [x] ユーザー登録(管理画面でできる)
~- [ ] ユーザー情報変更(管理画面でできる)~ いらなかった
- [x] ラベル追加・編集

↑適宜追加する

---------
**最初の画面(一覧が見れる)**

![todo-1](https://user-images.githubusercontent.com/14156156/41572690-1a5805f8-73b4-11e8-8a52-3f3a85c3ded3.JPG)

**タスクの追加・編集画面**
![todo-2](https://user-images.githubusercontent.com/14156156/41572739-4c5e5b9c-73b4-11e8-8f0b-0afbfc351525.JPG)

**Comment by tsumichan** [comment]
## ごっちゃんさんにレビューしていただいた

画面はだいたい良さそう

あと検索をつけるのを忘れていた


## 修正
**最初の画面(一覧が見れる)**
![img_9083](https://user-images.githubusercontent.com/14156156/41573821-916f6cf8-73b9-11e8-94ff-f70357fe4dc8.JPG)

**タスクの追加・編集画面**

![img_9084](https://user-images.githubusercontent.com/14156156/41573845-abd45464-73b9-11e8-85b7-e04edd925a09.JPG)


とりあえずこれで進める。
管理画面はタスク管理機能がひととおりできてから考える

**Comment by shiro16** [comment]
もう出来たじゃんという話をした

**Comment by tsumichan** [comment]
完成したので閉じます

最終的にこうなった

![image](https://user-images.githubusercontent.com/14156156/46279175-5a4ae900-c5a3-11e8-934c-873ebf16bb2c.png)


最初に決めたプロトタイプとほぼ変わらずになった
実際作ってみてると「ここはこうした方が使いやすいな」とかいろいろ出てきたので
都度いい感じにしてみたり、いい感じにしてみたものをレビューしてもらえたりしてよかった（感想）
