### ISSUE TITLE
【ご相談】フォームを囲う要素は何が妥当ですか？

### ISSUE THREAD

**Issue by tsumichan** [tsumichan/todo-app#13]
## 前提

- [万葉さんのカリキュラム](https://github.com/everyleaf/el-training)を使って、Todo管理アプリをひとりでいちから作っています
    - 仕様については[こちら](https://github.com/everyleaf/el-training/blob/master/docs/el-training.md)のREADMEをご覧ください！
- 社内のエンジニアのみなさんにレビューをいただきながらやっています
- いまは https://github.com/tsumichan/todo-app/pull/12 にて、タスクの登録処理をつくっています

## 聞きたいこと

フォームを作るとき、私はフォームを`div`で囲んだのですが、
どうするのが妥当だと思いますか？

`div`で囲んだ理由：https://github.com/tsumichan/todo-app/pull/12#discussion_r198370738

HTMLは学生の頃に書いていたことがあるのですが、
適切な構成まではあまり考えて書いたことがないので、いろいろご意見をいただきたいです！

よろしくお願いします 🙏

**Comment by shikakun** [comment]
### div か p か

まず、このアプリケーションのドキュメントタイプが [HTML5](https://github.com/tsumichan/todo-app/blob/master/app/views/layouts/application.html.slim#L1) という前提を確認したうえで、改めて div 要素と p 要素の意味を調べてみました。
（余談ですが、ブラウザを開発している人たちのドキュメントという理由で MDN を信頼しています… ほんとうは仕様書を読んだほうがよいのですが、いま HTML の仕様書は W3C と WHATWG の 2 つの団体によるドキュメントが存在するために、どちらを読んだらいいのかややこしいのです。）
:link: [&lt;div&gt;: コンテンツ分割要素 - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/div)
:link: [&lt;p&gt;: 段落要素 - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/p)

このドキュメントによると、 @tsumichan のおっしゃる通り、 p 要素はテキストの段落を意味するもので、 div 要素は特に意味がない（！）ということでした。よって、 div 要素か p 要素か… というと、ぼくも div 要素のほうが適していると思いました。

### label はどうか

さらに、ほかの選択肢はないか考えてみたいと思います。

label 要素は、フォームのそれぞれの項目のキャプションを指定できる HTML 要素です。
:link: [<label> - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/label)

今回の例で label 要素をつかってマークアップするなら、以下のようなマークアップになるでしょうか。

```html
<label>
  タスク名
  <input type="text" name="title">
</label>

<label>
  タスクの説明
  <textarea name="description"></textarea>
</label>
```

このようにマークアップすることで、「タスク名」というテキストと `<input type="text" name="title">` が関連づけられ、ブラウザを操作しているときにテキストをクリックするとテキストフォームが focus されるようになります。

しかし、 label 要素は、対象の要素に id 属性と、 label 要素に for 属性を指定することで、要素の外に input や textarea 要素があるマークアップも可能です。

```html
<label for="title">タスク名</label>
<input type="text" name="title" id="title">

<label for="description">タスクの説明</label>
<textarea name="description" id="description"></textarea>
```

今回は Rails のヘルパーを利用しているので、 @tsumichan が書かれているマークアップでも自動的に関連づけられるマークアップがされるはずです。

### Twitter Bootstrap はどうか

ここで、ほかの人たちはどのようにマークアップをしているのも見てみるといいのかな… と思いました。 Twitter Bootstrap は、世界でいちばん使われているといっても過言ではない CSS フレームワークのひとつであり、それだけさまざまな人たちが関わっているので、集合知によって適切なマークアップが検討されているはずです。

以下は、 Twitter Bootstrap のドキュメントに書かれている form 要素のマークアップ例です。

```html
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

:link: [Forms · Bootstrap](https://getbootstrap.com/docs/4.1/components/forms/)

`<div class="form-group">` 、つまり div 要素で囲っていることがわかります。

### で、結局どうしたらいいの？

- 今回の場合（フォームのひとかたまりを区切りたい、特に意味はない）は div で適切だと思いました 🎉 
- そのほかの選択肢を知っていても損はありませんし、知らないときに調べられる方法を知っているとよいと思います。ひとりでわからなかったら、デザイナーでも誰でも相談して、いっしょに適切なマークアップを探っていきましょう 👍

**Comment by tsumichan** [comment]
@shikakun 
最高すぎます、ありがとうございます！！！
MDN、あんまりちゃんと読んだことがなかったのですが、困ったときはドキュメントも見てみるべきですね 👀 

他の方のご意見もお待ちしております〜〜〜！

**Comment by tsumichan** [comment]
ひとまずは`div`を使っていくということで進めていきたいと思いますので、このissueはcloseさせていただきます 🙏 

まだ他にもご意見があれば伺いたいので、ぜひお願いします〜！！！

**Comment by june29** [comment]
@kentaro さんからも指摘があったと思うけど、この Issue のタイトルを内容に即したものに変えておくとよさそう？

**Comment by tsumichan** [comment]
@june29 
確かに！！！

フォームを囲ってはない…「フォームのかたまりを区切る要素」とかだとイメージしづらいですかね？

**Comment by june29** [comment]
囲っているのは「フォーム内の入力項目」ってところかねぇ :thinking:
「フォームのかたまり」だとフォームが複数ありそうな気もしてくる :thinking:

**Comment by tsumichan** [comment]
「フォーム内の入力エリア」とか思いついたんですけど、
ラベルも含まれているので「フォーム内の入力項目」の方が妥当そうだなと思いました

ご指摘ありがとうございます！ 🙇
