### ISSUE TITLE
データ構造を考える

### ISSUE THREAD

**Issue by tsumichan** [tsumichan/todo-app#2]
画面設計ができてから考える

**Comment by tsumichan** [comment]
## とりあえず考えてみたやつ

![img_9082](https://user-images.githubusercontent.com/14156156/41573919-07842e9c-73ba-11e8-9a9c-94f01d0fffe9.JPG)

**Comment by tsumichan** [comment]
## レビューいただいた

- `user_name`じゃなくても、userモデルなのでわかるので`name`でよさそう
- ラベルがmodelにないので追加する

**Comment by tsumichan** [comment]
あと 時間系のカラムは`_at`をつけるお作法があるので、`limit_at`にする

と書きながら思ったけど、`limit`って時間制限っぽい意味があるのでタスクの期限には向かない気がしてきた

**Comment by tsumichan** [comment]
## レビューいただいたその2

- ラベルは`task_model`が持つのではなく、独立したモデルにする
- 中間モデルを作って、`task_label`モデルとする

**こんな感じ**
![2018-06-19 12 02 17_3](https://user-images.githubusercontent.com/14156156/41584307-ef496270-73e1-11e8-8533-711c3b1cfec8.jpg)

limitの話をするのを忘れた。

**Comment by june29** [comment]
期限を表すカラムの名前について :star2:

時刻を指すカラムの名前を `*_at` にする慣習があるのは、その通り！ばっちりです。

ほいで @tsumichan が出してくれている案に `limit_at` というのがあるけれど、このときの `limit` って名詞のつもりで置きましたか？それとも動詞のつもりで置きましたか？

**Comment by june29** [comment]
紙とペンで思考を整理していくのは大変にグッドだと思います :ok_hand:

**Comment by tsumichan** [comment]
>ほいで @tsumichan が出してくれている案に limit_at というのがあるけれど、このときの limit って名詞のつもりで置きましたか？それとも動詞のつもりで置きましたか？

名詞のつもりでいました！
`limit`だけだと時間であることがわかりにくいので`_at`つけてればいいかなあと思っていたのですが、よく考えると名詞に`_at`つくの謎いですね…

**Comment by june29** [comment]
それに気付いてもらえたのなら大収穫です！一例として `created_at` について考えてみると、

> This record was created at 2018-06-20 10:00

みたいな英文が先にあっての `created_at` なわけです。ただ `_at` をつければ OK ということではないのでした〜 :dash: というわけで、もっかい考えてみて！:wink:

**Comment by tsumichan** [comment]
@june29 
締切、みたいな意味だと`close`とかになるのかなあと思ったんですが、
それだと期限とはちょっと違うニュアンスになりそうな気がするんですよね(強制的に終わりになる感じがする)

それならまだ`deadline`とかのほうがいいかなあと思うのですが、`_at`がつかないけど時間が入るカラムが存在するのってあんまり良くないとかあるんでしょうか 🤔

**Comment by june29** [comment]
たしかに `close_at` だと「閉館時刻」的なニュアンスを感じますね :bulb: 

絶対に `*_at` にしなきゃいけないというルールはありませんが、ぼく個人のスタンスで言えば、Rails でやっていく以上は Rails way に乗っかるのを基本としています。

`deadline` は「締切」感があっていいですね。難点を挙げるとしたら「日かな？時刻かな？」がカラム名からは判断できないところでしょうか。

これからこういう会話を重ねることになる配属先チームのレイルズピープルたちに意見を求めてみるのもよさそう！

**Comment by tsumichan** [comment]
## 昼会で聞いてみた

**limitについて**

`deadline`と`due_time`どっちかが良さそう〜という気持ちになってきた

- 海外のサービスを見てみるとよさそう、というアドバイス
    - `due_date`とか`due_time`が多いっぽい

- `deadline`の締切感(パッと見てイメージができる)
- 時間か？日付か？というのはあんまり気にしなくても良さそう
    - n日中、という締切の背後には「23：59まで」という時間が存在するので
- しかし型が明示的ではない
- `due_time`も近いニュアンス
- `time`があることにより、時間だということがわかりやすい

- `_at`をつけられない場合もあるよね〜というお話

**Comment by tsumichan** [comment]
## limit の話

チームのすごいエンジニアの方々によると、
`due at`という言い方があるようなので、`due_at`で一旦決めることにしました。
`_at`があることでRailsのお作法にのっとることができる！

**Comment by tsumichan** [comment]
こちらも`due_at`のままで特に問題もなく完成できたので閉じます。

カリキュラム進めていくうちに Taskだけじゃなくて他のモデルも追加していたけど
その都度issue立てたりして他の人にも見てもらえる機会を作っておけばよかったなと反省
（実際、https://github.com/tsumichan/todo-app/pull/47#issuecomment-423108406 でも指摘されているし、あやうく考え直しになるところだった）

データ構造とか設計考えるだけじゃなくて、細かいところ（カラム名どうしたら良いか？とか）もじっくり考える機会になり、学びがありまくりました。
チームとかいろんな人に相談してみてよかったな〜と思ったのでこれからもどんどん相談していろんな意見を聞いていきたいなと思いました（感想）
